---
- name: "Download Logstash's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-x86_64.rpm"
    dest: "files/logstash-{{ logstash_version }}-x86_64.rpm"
  register: download_logstash
  delegate_to: localhost
  until: download_logstash is succeeded
  when: logstash_install_type == 'remote'
- name: Copy Logstash to managed node
  copy:
    src: "files/logstash-{{ logstash_version }}-x86_64.rpm"
    mode: 0755
    dest: "/tmp/logstash-{{ logstash_version }}-x86_64.rpm"